#!/usr/bin/env node
// Live, watchable demo — not an automated test. Run `npm start` in one
// terminal, then `npm run demo` in another, and watch the tree react in
// real time: modifies, adds, deletes, a rename, a long name, unicode names,
// deep nesting, a huge file (good for trying the diff-view scroll), rapid
// re-edits (flash re-trigger), a bulk directory, and a binary file.
//
// Everything happens under demo-playground/, a real tracked folder in this
// repo. Each run first folds any leftover changes from the previous run
// into a commit, then resets to a fresh baseline, then makes live changes
// on top of that baseline — so the tool always has something real to show
// as modified/added/deleted since the last commit. It's left dirty on
// purpose at the end so you can keep browsing it in the tool; run again
// whenever you want a fresh sequence.

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const PLAYGROUND_NAME = "demo-playground";
const PLAYGROUND = join(ROOT, PLAYGROUND_NAME);

function git(args) {
  return execFileSync("git", args, { cwd: ROOT, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
}

function hasStagedChanges() {
  try {
    execFileSync("git", ["diff", "--cached", "--quiet", "--", PLAYGROUND_NAME], { cwd: ROOT });
    return false;
  } catch {
    return true;
  }
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function write(relPath, content) {
  const full = join(PLAYGROUND, relPath);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, content);
}

function step(msg) {
  console.log(`\n▸ ${msg}`);
}

async function main() {
  if (existsSync(PLAYGROUND)) {
    step("Folding in any leftover changes from a previous demo run...");
    git(["add", "-A", "--", PLAYGROUND_NAME]);
    if (hasStagedChanges()) git(["commit", "-q", "-m", "demo: fold in previous run"]);
  }

  step("Resetting demo-playground to a fresh baseline...");
  rmSync(PLAYGROUND, { recursive: true, force: true });
  write("README.md", "# Demo playground\n\nGenerated by scripts/demo.mjs. Safe to delete.\n");
  write("src/util.js", "export function util() {\n  return 1;\n}\n");
  write("src/widgets/button.js", "export function Button() {\n  return null;\n}\n");
  write("assets/image.bin", "");
  writeFileSync(join(PLAYGROUND, "assets/image.bin"), Buffer.from([1, 2, 3, 4, 5]));
  write("untouched/quiet.js", "export const quiet = true;\n");
  git(["add", "-A", "--", PLAYGROUND_NAME]);
  git(["commit", "-q", "-m", "demo: baseline"]);

  console.log("Baseline committed.");
  console.log(`If you haven't already, run "npm start" in another terminal now.`);
  await sleep(5000);

  step("Modifying a tracked file...");
  write("src/util.js", "export function util() {\n  return 2; // changed live\n}\n");
  await sleep(2500);

  step("Adding a deeply nested new file (10 levels down)...");
  const deep = Array.from({ length: 10 }, (_, i) => `level-${i}`);
  write(join(...deep, "deep.js"), "export const deep = true;\n");
  await sleep(2500);

  step("Adding a file with a very long name...");
  write(`a-file-with-an-extremely-long-name-${"x".repeat(150)}.js`, "export const longName = true;\n");
  await sleep(2500);

  step("Adding files with unicode/emoji names...");
  write("emoji-🔥-file.js", "export const fire = true;\n");
  write("café-Ω-unicode.js", "export const unicode = true;\n");
  await sleep(2500);

  step("Creating a large file (~3000 lines), then modifying a chunk of it...");
  const lines = Array.from({ length: 3000 }, (_, i) => `line ${i} — filler text to bulk it up`);
  write("src/huge.js", lines.join("\n") + "\n");
  await sleep(2000);
  for (let i = 1200; i < 1260; i++) lines[i] = `CHANGED line ${i}`;
  write("src/huge.js", lines.join("\n") + "\n");
  console.log("  -> open it in the tool now (enter/o) and try scrolling the diff (j/k, d/u)");
  await sleep(4500);

  step("Deleting a tracked file...");
  rmSync(join(PLAYGROUND, "assets/image.bin"));
  await sleep(2500);

  step("Renaming a tracked file...");
  git(["mv", `${PLAYGROUND_NAME}/src/widgets/button.js`, `${PLAYGROUND_NAME}/src/widgets/button-renamed.js`]);
  await sleep(2500);

  step("Rapid-fire edits on one file — watch the flash re-trigger...");
  for (let i = 0; i < 5; i++) {
    write("src/util.js", `export function util() {\n  return ${i}; // rapid edit ${i}\n}\n`);
    await sleep(400);
  }
  await sleep(2000);

  step("Adding ~50 files into a new directory (badge count + collapse check)...");
  for (let i = 0; i < 50; i++) write(`bulk/file-${String(i).padStart(2, "0")}.js`, `export const n = ${i};\n`);

  console.log("\nDone. demo-playground/ is left dirty on purpose so you can keep browsing it in the tool.");
  console.log(`"untouched/quiet.js" was never touched — its directory should stay collapsed with no badge.`);
  console.log("Run `npm run demo` again anytime for a fresh sequence. Say the word when you want it removed.");
}

main();
